# Core Ranking Categories
boardgame:
  complexity: 3.0
  strategic_value: 3.5
  interaction_value: 3.2
  description: 総合ボードゲームランキング。一般的な複雑さを持つゲームが中心となり、多様なメカニクスとテーマを包含する。

# Strategic Categories
strategygames:
  complexity: 4.2
  strategic_value: 4.8
  interaction_value: 3.8
  description: 戦略ゲームのランキング。複雑な意思決定と長期的計画が重視され、深い戦略的思考を要求するゲームが対象。

wargames:
  complexity: 4.5
  strategic_value: 4.7
  interaction_value: 4.0
  description: ウォーゲームのランキング。非常に複雑な軍事シミュレーションを含み、詳細な戦術・戦略的要素と歴史的背景が特徴。

abstracts:
  complexity: 3.8
  strategic_value: 4.2
  interaction_value: 2.7
  description: アブストラクトゲームのランキング。テーマよりもメカニクスを重視した、純粋な戦略性を追求するゲームが中心。

# Customizable Categories
customizable:
  complexity: 3.9
  strategic_value: 4.3
  interaction_value: 3.5
  description: カスタマイズ可能なゲームのランキング。デッキ構築やキャラクター育成など、プレイヤーが自由にゲーム要素をカスタマイズできる点が特徴。

# Thematic Categories
thematic:
  complexity: 3.5
  strategic_value: 3.7
  interaction_value: 4.0
  description: テーマティックゲームのランキング。ストーリーや世界観を重視し、テーマに沿った没入感のあるゲーム体験を提供するタイトルが対象。

# Family and Casual Categories
familygames:
  complexity: 2.3
  strategic_value: 2.8
  interaction_value: 3.5
  description: ファミリーゲームのランキング。やや簡単なルールで幅広い年齢層が楽しめる、アクセシビリティの高いゲームが中心。

partygames:
  complexity: 1.7
  strategic_value: 1.5
  interaction_value: 4.5
  description: パーティーゲームのランキング。シンプルなルールと高い社交性が特徴で、エンターテイメント性を重視したゲームが対象。

childrensgames:
  complexity: 1.4
  strategic_value: 1.3
  interaction_value: 2.8
  description: 子供向けゲームのランキング。非常にシンプルなルールと教育的要素を持ち、若年層でも楽しめる設計になっているゲームが中心。